/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class SignIn extends javax.swing.JFrame {
    public SignIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stu_staff = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        logIn = new java.awt.Button();
        stdlog = new javax.swing.JRadioButton();
        stafflog = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        Sign_in = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username (*)");

        jLabel2.setText("Password (*)");

        logIn.setLabel("Log In");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });

        stu_staff.add(stdlog);
        stdlog.setText("Student");
        stdlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdlogActionPerformed(evt);
            }
        });

        stu_staff.add(stafflog);
        stafflog.setText("Staff");
        stafflog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stafflogActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("COURSE REGISTRATION");

        Sign_in.setBackground(new java.awt.Color(198, 198, 181));
        Sign_in.setText("Sign Up");
        Sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_inActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        jLabel4.setText("For New User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(stdlog)
                                .addGap(45, 45, 45)
                                .addComponent(stafflog)
                                .addGap(154, 154, 154))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(logIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(Sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdlog)
                    .addComponent(stafflog)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sign_in, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stdlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdlogActionPerformed

    }//GEN-LAST:event_stdlogActionPerformed

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        // TODO add your handling code here:
        try{
            String uname,pwd;                           //get username and password
            int flag2;
            uname = username.getText();
            pwd = password.getText();
            String info[]=new String[1]; 
            info[0]=uname;
            if(uname==null | pwd==null){                //data in both fields
                flag2=0;
                JOptionPane.showMessageDialog(this,"Insert data in all fields");
            }
            else{
                flag2=1;
            }
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Kshitija123!")) {
                if(flag2==1){                               //check if staff or student
                PreparedStatement ps = con.prepareStatement("select is_student from user where name = ? and password = ?;");
                ps.setString(1,uname);
                ps.setString(2,pwd);
                ResultSet rs = ps.executeQuery();
                Courses c=new Courses();
                StudentCourses s=new StudentCourses();
                if(rs.next())//returning false
                {
                    boolean flag=rs.getBoolean("is_student");
                    JOptionPane.showMessageDialog(this,"Login Successful");
                    this.setVisible(false);
                    
                    if(flag==true)    //student then open studentcourse
                    { 
                         //put username value in the array info.
                        s.setVisible(true);
                        s.main(info);
                    }
                    else{       //staff then open courses
                         c.setVisible(true);
                         c.main(info);
                     }
                    set_null();
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Incorrect Credentials! Please re-enter correct info or SignIn");
                }
            }
        }
        }
        catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        catch(HeadlessException e){
            System.out.println(e.getMessage());    
        }   
    }//GEN-LAST:event_logInActionPerformed
public void set_null(){
    String a=null;
    username.setText(a);
    password.setText(a);
}
    private void Sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_inActionPerformed
       try{
            String uname,pwd;
            boolean person=false;
            boolean admin = false;
            uname = username.getText();
            pwd = password.getText();
            int flag=0;
            if(stu_staff.getSelection()==null | uname==null | pwd==null)
            {
               JOptionPane.showMessageDialog(this,"Insert data in all fields!");
            }
            else {
                flag=1;
                if (stdlog.isSelected()){
                    person=true;
                }  
                 else{
                    person=false;
                }
            }
            Class.forName("com.mysql.jdbc.Driver");
            if(flag==1)
            {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Kshitija123!");
                    
                        PreparedStatement ps = con.prepareStatement("select * from user where name = ? and password = ?;");
                        ps.setString(1,uname);                          //username exits
                        ps.setString(2,pwd);
                        ResultSet r2 = ps.executeQuery();
                        if(r2.next())
                        {
                            JOptionPane.showMessageDialog(this,"Username already in use!");
                        }
                        else
                        { 
                            PreparedStatement p2 = con.prepareStatement("insert into user values(?,?,?,?);");
                            p2.setString(1,uname);
                            p2.setString(2,pwd);
                            p2.setBoolean(3,person);
                            p2.setBoolean(4,admin);
                            int flag2 = p2.executeUpdate();
                            if(flag2!=0)
                            {
                                JOptionPane.showMessageDialog(this,"Inserted Successfully! Log In Now.");
                            } 
                            else
                            {
                                 JOptionPane.showMessageDialog(this,"Insertion Unsuccessful.Try again!");
                            }
                        }
                    }
            
            //set_null();
       }
        catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this,"Username exists! Select new one");   
        }
    }//GEN-LAST:event_Sign_inActionPerformed

    private void stafflogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stafflogActionPerformed
    }//GEN-LAST:event_stafflogActionPerformed

    /**
     * @param args
     * @throws java.lang.Exception
     * @para
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sign_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private java.awt.Button logIn;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton stafflog;
    private javax.swing.JRadioButton stdlog;
    private javax.swing.ButtonGroup stu_staff;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

   
}
